### ISSUE TITLE
AttributeError: 'str' object has no attribute 'write'

### ISSUE THREAD

**Issue by rjcamatos** [mattwach/fygen#6]
#!/usr/bin/python
"""Minimalist sweep example that sweeps between 1khz and 10khz."""

import sys

sys.path.append('../..')

# pylint: disable=wrong-import-position
import fygen

fy = fygen.FYGen(debug_level=1, port='COM3')
fy.set(0, wave='sin', freq_hz=1000, enable=True)
fy.set_sweep(
    mode=fygen.SWEEP_FREQUENCY,
    start_freq_hz=1000,
    end_freq_hz=10000,
    time_seconds=10)

print('Please presss the adjustment knob on the signal generator to '
      'begin the sweep')

-------------------------------------------------------------------------------------
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\myself\Documents\GitHub\fygen\examples\sweep\sweep_freq.py =
Traceback (most recent call last):
  File "C:\Users\myself\Documents\GitHub\fygen\examples\sweep\sweep_freq.py", line 12, in <module>
    fy.set(0, wave='sin', freq_hz=1000, enable=True)
  File "C:\Users\myself\Documents\GitHub\fygen\examples\sweep\../..\fygen.py", line 382, in set
    if not self._set_for_channel(c, chan_dict):
  File "C:\Users\myself\Documents\GitHub\fygen\examples\sweep\../..\fygen.py", line 470, in _set_for_channel
    self.send(command)
  File "C:\Users\myself\Documents\GitHub\fygen\examples\sweep\../..\fygen.py", line 310, in send
    self.port.write(data)
AttributeError: 'str' object has no attribute 'write'

**Comment by mattwach** [comment]
Hello,

Instead of

fy = fygen.FYGen(debug_level=1, port='COM3')

try this:

fy = fygen.FYGen(debug_level=1, serial_path='COM3')

or

fy = fygen.FYGen('COM3', debug_level=1)

The port option takes a file object, such as sys.stdin.  It's main purpose would be to view the commands sent to the device as explained here: https://github.com/mattwach/fygen#streaming-output-to-a-file

**Comment by rjcamatos** [comment]
Sir,
With the two options it output the same error:

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64
bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART:
C:\Users\myself\Documents\GitHub\fygen\examples\sweep\sweep_freq.py =
Traceback (most recent call last):
  File
"C:\Users\myself\Documents\GitHub\fygen\examples\sweep\sweep_freq.py", line
11, in <module>
    fy = fygen.FYGen('COM3', debug_level=1)
  File
"C:\Users\myself\Documents\GitHub\fygen\examples\sweep\../..\fygen.py",
line 260, in __init__
    self.port = serial.Serial(
AttributeError: module 'serial' has no attribute 'Serial'

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

mattwach ***@***.***> escreveu no dia quarta, 19/01/2022 à(s)
17:27:

**Comment by mattwach** [comment]
That is a different error.  It's saying that the serial module you loaded is not pyserial.

This should work:

$ python3
>>> import serial
>>> serial.Serial
<class 'serial.serialposix.Serial'>

but, based on the error you say, the serial.Serial part will throw an error.

To install pyserial, here is the documentation: https://pyserial.readthedocs.io/en/latest/pyserial.html

You might also try the examples on the pyserial page to make sure it is installed correctly: https://pyserial.readthedocs.io/en/latest/shortintro.html

**Comment by rjcamatos** [comment]
Ok, tanks It works out....
But for amplitude, duty and offset the values don't change on the
instrument, just change the frequency value.
By the way, why need to press the knob on the instrument to start the
sweep function ?
There is no way to start automatically ?
"Please presss the adjustment knob on the signal generator to begin the sweep"

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC
v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\myself\Documents\GitHub\fygen\examples\sweep\sweep_amplitude.py
UMO -> FY6900H-100M
RMW -> 0
RMF -> 00000000.000000
RMA -> 30000
RMO -> 0
RMP -> 0
RMD -> 50000
RMN -> 255
WMW01 ->
WMF00001000000000 ->
WMA5.00 ->
RMW -> 0
RMF -> 00000000.000000
RMA -> 30000
WMW01 ->
WMF00001000000000 ->
WMA5.00 ->
RMW -> 0
RMF -> 00000000.000000
RMA -> 30000
WMW01 ->
WMF00001000000000 ->
WMA5.00 ->
SBE0 ->
SOB1 ->
STI2.00 ->
SST3.300 ->
SEN5.000 ->
Please presss the adjustment knob on the signal generator to begin the sweep


--------------------------------------------------------------------------------

mattwach ***@***.***> escreveu no dia quarta, 19/01/2022
à(s) 18:33:

**Comment by mattwach** [comment]
Read this section:

https://github.com/mattwach/fygen#sweep

My unit has a bug that requires a press of the knob but for units that don't have this bug (if there are any) a software setting can turn off the prompt.

**Comment by rjcamatos** [comment]
Tanks for reply :)

A quinta, 20/01/2022, 18:23, mattwach ***@***.***> escreveu:
